jdg_java_version: "{{ item.java_version|default(java_latest) }}"
jdg_java_postfix: "{{ (jdg_java_version[0]|int < 9)|ternary(java_arch + '.tar.gz',java_arch + '_bin.tar.gz' ) }}"
jdg_java_archive_name: "{{ (jdg_java_version[0]|int < 9)|ternary( 'jdk-' + jdg_java_version + '-linux-' + java_postfix, 'jdk-' + jdg_java_version + '_linux-' + jdg_java_postfix ) }}"
jdg_java_home: "{{ (jdg_java_version[0]|int < 9)|ternary( wxx_dirs.java_dir + '/jdk1.' + jdg_java_version|regex_replace('^(\\d+)u(\\d+)$', '\\1.0_\\2'), wxx_dirs.java_dir + '/jdk-' + jdg_java_version ) }}"
jdg_instance_name: "{{ item.name }}"
jdg_instance_ensure: "{{ item.ensure }}"
jdg_instance_status: "{{ item.status }}"
jdg_instance_enable: "{{ (jdg_instance_ensure == 'present')|ternary(item.enable, False) }}"
jdg_http_port: "{{ jdg_instance_name|regex_replace('[a-zA-Z]+','')|int }}"
jdg_port_offset: "{{ jdg_instance_name|regex_replace('[a-zA-Z]+','')|int - 8080|default(0) }}"
jdg_version: "{{ item.jdg_version|default(jdg_latest) }}"
jdg_archive_name: "jboss-datagrid-{{ jdg_version }}-server.zip"
jdg_version_major: "{{ jdg_version.split('.')[0] }}"
jdg_version_minor: "{{ jdg_version.split('.')[1] }}"
jdg_version_patch: "{{ jdg_version.split('.')[2] }}"
jdg_cli_base_port: "{{ (jdg_version_major|int > 6)|ternary(9990,9999) }}"
jdg_cli_port: "{{ jdg_cli_base_port|int + jdg_port_offset|int }}"
jdg_user: "{{ item.jdg_user|default('webuser') }}"
jdg_group: "{{ item.jdg_group|default('jasgroup') }}"
jdg_jboss_base_dir: "{{ wxx_dirs.app_dir }}/{{ jdg_instance_name }}"
jdg_jboss_home_dir: "{{ wxx_dirs.app_dir }}/jboss-datagrid-{{ jdg_version }}-server-{{ jdg_http_port }}"
jdg_module_base_path: "{{ item.module_base_path | default('modules/system/layers/base') }}"
jdg_modules: "{{ item.modules|default([]) }}"
jdg_apps: "{{ item.apps|default([]) }}"
jdg_jboss_opts: "{{ item.jboss_opts|default([]) }}"
jdg_java_opts: "{{ item.java_opts }}"
jdg_configuration_xml_name: "{{ item.configuration_xml.name|default('standalone.xml') }}"
jdg_configuration_xml_deploy: "{{ item.configuration_xml.deploy|default(False) }}"
jdg_configuration_xml_src: "{{ item.configuration_xml.src|default('') }}"
jdg_configuration_xml_remote_src: "{{ item.configuration_xml.remote_src|default('no') }}"
jdg_configuration_inserts:  "{{ item.configuration_inserts|default([]) }}"
jdg_config_files: "{{ item.config_files|default([]) }}"
jdg_starttimeout: "{{ item.starttimeout|default(60) }}"
jdg_stoptimeout: "{{ item.stoptimeout|default(60) }}"
jdg_maint_stop_delay: "{{ item.maint_stop_delay|default('15m') }}"
jdg_ld_library_path: "{{ item.ld_library_path|default([]) }}"
jdg_appdynamics: "{{ item.appdynamics|default({}) }}"
jdg_appdynamics_ensure: "{{ jdg_appdynamics.ensure|default('') }}"
jdg_appdynamics_properties: "{{ jdg_appdynamics.properties|default({}) }}"
