---
- name: Add or remove management path for sun jdk module
  lineinfile:
    path: "{{ eap_jboss_base_dir }}/{{ eap_module_base_path }}/sun/jdk/main/module.xml"
    insertafter: '.*<paths>.*'
    line: '                <path name="com/sun/management"/>'
    state: "{{ eap_path_sun_jdk_management }}"
  register: sun_jdk_result
  notify: "restart eap instance"

- name: Manage eap_refresh_list for sun jdk module
  set_fact: eap_refresh_list={{ eap_refresh_list + [ eap_instance_name ] }}
  when: sun_jdk_result.changed
  no_log: True
