---
## Deploy app
 
- name: "Deploy apps for {{ eap_instance_name }} check mode"
  copy:
    src: "{{ app.src }}/{{ app.file }}"
    dest: "{{ eap_jboss_base_dir }}/standalone/deployments/{{ app.file }}"
    remote_src: "{{ app.remote_src }}"
  register: deploy_result
  notify: "restart eap instance"
  with_items: "{{ eap_apps }}"
  loop_control:
    loop_var: app
  no_log: False
  when: app.ensure == 'present'
  check_mode: yes

- name: "Stop EAP instance {{ eap_instance_name }}"
  shell: "{{ wxx_dirs.app_dir }}/{{ eap_instance_name }}/bin/proc.sh stop"
  args:
    chdir: "{{ wxx_dirs.app_dir }}/{{ eap_instance_name }}/bin"
    executable: /bin/bash
  when: deploy_result.changed

- name: "Deploy apps for {{ eap_instance_name }}"
  copy:
    src: "{{ app.src }}/{{ app.file }}"
    dest: "{{ eap_jboss_base_dir }}/standalone/deployments/{{ app.file }}"
    remote_src: "{{ app.remote_src }}"
  register: deploy_result
  notify: "restart eap instance"
  with_items: "{{ eap_apps }}"
  loop_control:
    loop_var: app
  no_log: False
  when: app.ensure == 'present'

- name: Manage eap_refresh_list for deployments
  set_fact: eap_refresh_list={{ eap_refresh_list + [ eap_instance_name ] }}
  when: elem.changed and  eap_instance_status == 'running'
  with_items: "{{ deploy_result.results }}"
  loop_control:
    loop_var: elem
  tags:
    - deploy
  no_log: True
  
## Undeploy app

- name: Remove app file
  file: 
    dest: "{{ eap_jboss_base_dir }}/standalone/deployments/{{ app.file }}"
    state: 'absent'
  with_items: "{{ eap_apps }}"
  register: undeploy_result
  loop_control:
    loop_var: app
  when: app.ensure == 'absent'
