tomcat_java_version: "{{ item.java_version|default(java_latest) }}"
tomcat_java_postfix: "{{ (tomcat_java_version[0]|int < 9)|ternary(java_arch + '.tar.gz',java_arch + '_bin.tar.gz' ) }}"
tomcat_java_archive_name: "{{ (tomcat_java_version[0]|int < 9)|ternary( 'jdk-' + tomcat_java_version + '-linux-' + java_postfix, 'jdk-' + tomcat_java_version + '_linux-' + tomcat_java_postfix ) }}"
tomcat_java_home: "{{ (tomcat_java_version[0]|int < 9)|ternary( wxx_dirs.java_dir + '/jdk1.' + tomcat_java_version|regex_replace('^(\\d+)u(\\d+)$', '\\1.0_\\2'), wxx_dirs.java_dir + '/jdk-' + tomcat_java_version ) }}"
tomcat_instance_name: "{{ item.name }}"
tomcat_instance_ensure: "{{ item.ensure }}"
tomcat_instance_status: "{{ item.status }}"
tomcat_instance_enable: "{{ (tomcat_instance_ensure == 'present')|ternary(item.enable, False) }}"
tomcat_version: "{{ item.tomcat_version|default(tomcat_latest) }}" 
tomcat_archive_name: "apache-tomcat-{{ tomcat_version }}.tar.gz"
tomcat_version_major: "{{ tomcat_version.split('.')[0] }}" 
tomcat_version_minor: "{{ tomcat_version.split('.')[1] }}"
tomcat_version_patch: "{{ tomcat_version.split('.')[2] }}"
tomcat_http_port: "{{ tomcat_instance_name|regex_replace('[a-zA-Z]+','')|int|default(8080) }}"
tomcat_port_offset: "{{ tomcat_instance_name|regex_replace('[a-zA-Z]+','')|int - 8080 }}"
tomcat_catalina_base: "{{ wxx_dirs.app_dir }}/{{ tomcat_instance_name }}"
tomcat_catalina_home: "{{ wxx_dirs.app_dir }}/apache-tomcat-{{ tomcat_version }}-{{ tomcat_http_port }}"
tomcat_config_files: "{{ item.config_files|default([]) }}"
tomcat_modules: "{{ item.modules|default([]) }}"
tomcat_keystores: "{{ item.keystores|default([]) }}"
tomcat_apps: "{{ item.apps|default([]) }}"
tomcat_user: "{{ item.tomcat_user|default('webuser') }}"
tomcat_group: "{{ item.tomcat_group|default('jasgroup') }}"
tomcat_java_opts: "{{ item.java_opts }}"
tomcat_catalina_opts: "{{ item.catalina_opts|default([]) }}"
tomcat_starttimeout: "{{ item.starttimeout|default(120) }}"
tomcat_stoptimeout: "{{ item.stoptimeout|default(120) }}"
tomcat_maint_stop_delay: "{{ item.maint_stop_delay|default('15m') }}"
tomcat_certs: "{{ item.certs|default([]) }}"
tomcat_ca_certs: "{{ item.ca_certs|default([]) }}"
tomcat_ld_library_path: "{{ item.ld_library_path|default([]) }}"
tomcat_appdynamics: "{{ item.appdynamics|default({}) }}"
tomcat_appdynamics_ensure: "{{ tomcat_appdynamics.ensure|default('') }}"
tomcat_appdynamics_properties: "{{ tomcat_appdynamics.properties|default({}) }}"
