---
- name: restart-eap
  shell: "{{ wxx_dirs.app_dir }}/{{ item }}/bin/proc.sh stop;nohup {{ wxx_dirs.app_dir }}/{{ item }}/bin/proc.sh start &"
  args:
    chdir: "{{ wxx_dirs.app_dir }}/{{ item }}/bin"
    executable: /bin/bash
  with_items: "{{ eap_refresh_list | unique }}"
  listen: "restart eap instance"
  no_log: False

- name: start_eap_instance
  shell: "nohup {{ wxx_dirs.app_dir }}/{{ item }}/bin/proc.sh start &"
  args:
    chdir: "{{ wxx_dirs.app_dir }}/{{ item }}/bin"
    executable: /bin/bash
  with_items: "{{ eap_start_list | unique }}"
  listen: "start eap instance"
  no_log: False
  when: item not in eap_refresh_list

- name: stop_eap_instance
  shell: "{{ wxx_dirs.app_dir }}/{{ item }}/bin/proc.sh stop"
  args:
    chdir: "{{ wxx_dirs.app_dir }}/{{ item }}/bin"
    executable: /bin/bash
  with_items: "{{ eap_stop_list | unique }}"
  listen: "stop eap instance"
  no_log: False
  when: item not in eap_refresh_list

