httpd_ensure: "{{ httpd.ensure|default('absent') }}"
httpd_enable: "{{ (httpd_ensure == 'present')|ternary(httpd.enable, False) }}"
httpd_state: "{{ httpd.state|default('stopped') }}"
httpd_serverroot: "{{ httpd.serverroot|default('/wxx/httpd') }}"
httpd_servername: "{{ httpd.servername|default(ansible_fqdn) }}"
httpd_servertokens: "{{ httpd.servertokens|default('ProductOnly') }}"
httpd_serversignature: "{{ httpd.serversignature|default('Off') }}"
httpd_documentroot: "{{ httpd.documentroot|default('/wxx/data/httpd/htdocs') }}"
httpd_rootdir: "{{ httpd.rootdir|default('/wxx/data/httpd') }}"
httpd_user: "{{ httpd.user|default('apache') }}"
httpd_group: "{{ httpd.group|default('apache') }}"
httpd_options: "{{ httpd.options|default('-Indexes +FollowSymLinks') }}"
httpd_conf_web: "{{ httpd.conf_web|default([]) }}"
httpd_vhosts: "{{ httpd.vhosts|default([]) }}"
httpd_vhosts_ssl: "{{ httpd.vhosts_ssl|default([]) }}"
httpd_modules: "{{ httpd.modules|default([]) }}"
httpd_mod_jk_ensure: "{{ httpd.mod_jk.ensure|default('present') }}"
httpd_ports: "{{ httpd.ports|join(' ')|default('80') }}"
httpd_maint_stop_delay: "{{ httpd.maint_stop_delay|default('15m') }}"
