wildfly_java_version: "{{ item.java_version|default(java_latest) }}"
wildfly_java_postfix: "{{ (wildfly_java_version[0]|int < 9)|ternary(java_arch + '.tar.gz',java_arch + '_bin.tar.gz' ) }}"
wildfly_java_archive_name: "{{ (wildfly_java_version[0]|int < 9)|ternary( 'jdk-' + wildfly_java_version + '-linux-' + java_postfix, 'jdk-' + wildfly_java_version + '_linux-' + wildfly_java_postfix ) }}"
wildfly_java_home: "{{ (wildfly_java_version[0]|int < 9)|ternary( wxx_dirs.java_dir + '/jdk1.' + wildfly_java_version|regex_replace('^(\\d+)u(\\d+)$', '\\1.0_\\2'), wxx_dirs.java_dir + '/jdk-' + wildfly_java_version ) }}"
wildfly_instance_name: "{{ item.name }}"
wildfly_instance_ensure: "{{ item.ensure }}"
wildfly_instance_status: "{{ item.status }}"
wildfly_instance_enable: "{{ (wildfly_instance_ensure == 'present')|ternary(item.enable, False) }}"
wildfly_http_port: "{{ wildfly_instance_name|regex_replace('[a-zA-Z]+','')|int }}"
wildfly_port_offset: "{{ wildfly_instance_name|regex_replace('[a-zA-Z]+','')|int - 8080|default(0) }}"
wildfly_cli_base_port: "{{ 9990 }}"
wildfly_cli_port: "{{ wildfly_cli_base_port|int + wildfly_port_offset|int }}"
wildfly_version: "{{ item.wildfly_version|default(wildfly_latest) }}"
wildfly_archive_name: "wildfly-{{ wildfly_version }}.Final.tar.gz"
wildfly_version_major: "{{ wildfly_version.split('.')[0] }}"
wildfly_version_minor: "{{ wildfly_version.split('.')[1] }}"
wildfly_version_patch: "{{ wildfly_version.split('.')[2] }}"
wildfly_user: "{{ item.wildfly_user|default('webuser') }}"
wildfly_group: "{{ item.wildfly_group|default('jasgroup') }}"
wildfly_jboss_base_dir: "{{ wxx_dirs.app_dir }}/{{ wildfly_instance_name }}"
wildfly_jboss_home_dir: "{{ wxx_dirs.app_dir }}/wildfly-{{ wildfly_version }}-{{ wildfly_http_port }}"
wildfly_module_base_path: "{{ item.module_base_path|default('modules/system/layers/base') }}"
wildfly_modules: "{{ item.modules|default([]) }}"
wildfly_apps: "{{ item.apps|default([]) }}"
wildfly_jboss_opts: "{{ item.jboss_opts|default([]) }}"
wildfly_java_opts: "{{ item.java_opts }}"
wildfly_configuration_xml_name: "{{ item.configuration_xml.name|default('standalone.xml') }}"
wildfly_configuration_xml_deploy: "{{ item.configuration_xml.deploy|default(False) }}"
wildfly_configuration_xml_src: "{{ item.configuration_xml.src|default('') }}"
wildfly_configuration_xml_remote_src: "{{ item.configuration_xml.remote_src|default('no') }}"
wildfly_configuration_inserts:  "{{ item.configuration_inserts|default([]) }}"
wildfly_config_files: "{{ item.config_files|default([]) }}"
wildfly_starttimeout: "{{ item.starttimeout|default(300) }}"
wildfly_stoptimeout: "{{ item.stoptimeout|default(60) }}"
wildfly_ld_library_path: "{{ item.ld_library_path|default([]) }}"
wildfly_appdynamics: "{{ item.appdynamics|default({}) }}"
wildfly_appdynamics_ensure: "{{ wildfly_appdynamics.ensure|default('') }}"
wildfly_appdynamics_properties: "{{ wildfly_appdynamics.properties|default({}) }}"

