---
## Install startup services
 
- block:

  - block:

    - name: "Manage init script for httpd-wxx"
      template:
        dest: "{{ base_dir}}/httpd/bin/init"
        src: init.j2
        mode: '0755'
      register: init_result
      no_log: False

    - name: "Deploy init script for httpd-wxx"
      shell: sudo cp "{{ base_dir }}/httpd/bin/init" "/etc/init.d/httpd-wxx"
      args:
        executable: /bin/bash
        warn: no
      no_log: False
      when: init_result.changed

    - name: "Deploy init service for httpd-wxx"
      shell: sudo chkconfig httpd-wxx on
      args:
        executable: /bin/bash
        warn: no
      no_log: False
      when: init_result.changed

    when: ansible_distribution_major_version|int < 7 

  - block:
    - name: "Manage unit script for httpd-wxx" 
      template:
        dest: "{{ base_dir }}/httpd/bin/unit"
        src: unit.j2
        mode: '0644'
      register: unit_result
      no_log: False

    - name: "Deploy unit script for httpd-wxx"
      shell: sudo cp "{{ base_dir }}/httpd/bin/unit" "/usr/lib/systemd/system/httpd-wxx.service"
      args:
        executable: /bin/bash
        warn: no
      no_log: False
      when: unit_result.changed

    - name: "Deploy systemd service for httpd-wxx"
      shell: sudo systemctl enable httpd-wxx
      args:
        executable: /bin/bash
        warn: no
      no_log: False
      when: unit_result.changed

    when: ansible_distribution_major_version|int > 6 

  when: httpd_enable == True

## Uninstall startup services

- block:

  - block:
    - name: "Remove init service for httpd-wxx"
      shell: sudo chkconfig httpd-wxx off
      args:
        executable: /bin/bash
        warn: no
        removes: "/etc/init.d/httpd-wxx"
      no_log: False

    - name: "Remove init script for httpd"
      shell: sudo rm -f "/etc/init.d/httpd-wxx"
      args:
        executable: /bin/bash
        warn: no
        removes: "/etc/init.d/httpd-wxx"
      no_log: False

    - name: "Remove init script source for httpd-wxx"
      file:
        path: "{{ base_dir }}/httpd/bin/init"
        state: absent
      no_log: False

    when: ansible_distribution_major_version|int < 7 

  - block:

    - name: "Remove systemd service for httpd-wxx"
      shell: sudo systemctl disable httpd-wxx
      args:
        executable: /bin/bash
        warn: no
        removes: "/etc/systemd/system/multi-user.target.wants/httpd-wxx.service"
      no_log: False

    - name: "Remove unit script for httpd-wxx"
      shell: sudo rm -f "/usr/lib/systemd/system/httpd-wxx.service"
      args:
        executable: /bin/bash
        warn: no
        removes: "/usr/lib/systemd/system/httpd-wxx.service"
      no_log: False

    - name: "Remove unit script source for httpd-wxx"
      file:
        path: "{{ base_dir }}/httpd/bin/unit"
        state: absent
      no_log: False

    when: ansible_distribution_major_version|int > 6 

  when: httpd_enable == False
