---
## Deploy keystores
 
- name: "Deploy keystores  for {{ tomcat_instance_name }}"
  copy:
    src: "{{ keystore.src }}/{{ keystore.name }}"
    dest: "{{ wxx_dirs.sec_dir }}/{{ keystore.name }}"
    remote_src: "{{ keystore.remote_src }}"
  register: keystore_result
  notify: "restart-tomcat"
  with_items: "{{ tomcat_keystores }}"
  loop_control:
    loop_var: keystore
  no_log: False
  when: keystore.ensure == 'present'

- name: "Manage tomcat_refresh_list for keystores for {{ tomcat_instance_name }}"
  set_fact: tomcat_refresh_list={{ tomcat_refresh_list + [ tomcat_instance_name ] }}
  when: elem.changed and tomcat_instance_status == 'running'
  with_items: "{{ keystore_result.results }}"
  loop_control:
    loop_var: elem
  tags:
    - deploy
  no_log: True

## Undeploy keystore

- name: "Remove keystores for {{ tomcat_instance_name }}"
  file: 
    dest: "{{ wxx_dirs.sec_dir }}/{{ keystore.name }}"
    state: 'absent'
  with_items: "{{ tomcat_keystores }}"
  loop_control:
    loop_var: keystore
  when: keystore.ensure == 'absent'
  no_log: True

